spring.application.name=TechnicalServiceManagement
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5433/technical_service
spring.datasource.username=postgres
spring.datasource.password=8442

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

